version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_backend
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput \
               && python3 manage.py initial && gunicorn --threads 3 --bind 0.0.0.0:8000 cnstodo.wsgi --timeout=120"
    restart: always
    volumes:
      - ./store:/app/store
    ports:
      - "8000:8000"
    env_file:
      - .env
volumes:
  todo: