# Generated by Django 4.2.7 on 2023-11-10 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Priority',
                'verbose_name_plural': 'Priorities',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField(verbose_name='Description')),
                ('task_creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('task_due_date', models.DateTimeField(blank=True, verbose_name='Date Due')),
                ('tags', models.TextField(blank=True)),
                ('task_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('task_priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.priority', verbose_name='Priority')),
                ('task_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.state', verbose_name='State')),
            ],
            options={
                'ordering': ['task_creation_date'],
            },
        ),
    ]
